export type WeaponId = "none" | "knife" | "pistol" | "worn-ak" | "short-mosin" | "rifle" | "smg" | "shotgun" | "pkm" | "amr" | "rpg";

export interface WeaponDefinition {
  id: WeaponId;
  name: string;
  description: string;
  raidCost: number;
  damage: number;
  pellets: number;
  spread: number;
  fireInterval: number;
  bulletSpeed: number;
  range: number;
  magazineSize: number;
  reserveAmmo: number;
  ammoPackAmmo: number;
  reloadTime: number;
  reloadStyle: "magazine" | "shell";
  reloadInsertTime: number;
  moveSpeed: number;
  moveSpreadPenalty: number;
  recoilPerShot: number;
  recoilRecoveryPerSecond: number;
  maxSpreadPenalty: number;
  focusMoveMultiplier: number;
  focusSpreadMultiplier: number;
  focusRecoveryMultiplier: number;
  noiseRadius: number;
  noiseScore: number;
  color: number;
}

export const WEAPONS: Record<WeaponId, WeaponDefinition> = {
  none: {
    id: "none",
    name: "No Primary",
    description: "Deploy with no primary weapon. Faster on the wallet, brutal on survivability.",
    raidCost: 0,
    damage: 0,
    pellets: 1,
    spread: 0,
    fireInterval: 0.3,
    bulletSpeed: 0,
    range: 0,
    magazineSize: 0,
    reserveAmmo: 0,
    ammoPackAmmo: 0,
    reloadTime: 0,
    reloadStyle: "magazine",
    reloadInsertTime: 0,
    moveSpeed: 238,
    moveSpreadPenalty: 0,
    recoilPerShot: 0,
    recoilRecoveryPerSecond: 0,
    maxSpreadPenalty: 0,
    focusMoveMultiplier: 1,
    focusSpreadMultiplier: 1,
    focusRecoveryMultiplier: 1,
    noiseRadius: 0,
    noiseScore: 0,
    color: 0x94a3b8
  },
  knife: {
    id: "knife",
    name: "Field Knife",
    description: "Cheap fixed blade for silent room kills, desperate pushes, and last-ditch close work.",
    raidCost: 20,
    damage: 52,
    pellets: 1,
    spread: 0.02,
    fireInterval: 0.48,
    bulletSpeed: 0,
    range: 58,
    magazineSize: 0,
    reserveAmmo: 0,
    ammoPackAmmo: 0,
    reloadTime: 0,
    reloadStyle: "magazine",
    reloadInsertTime: 0,
    moveSpeed: 282,
    moveSpreadPenalty: 0,
    recoilPerShot: 0,
    recoilRecoveryPerSecond: 0,
    maxSpreadPenalty: 0,
    focusMoveMultiplier: 1,
    focusSpreadMultiplier: 1,
    focusRecoveryMultiplier: 1,
    noiseRadius: 42,
    noiseScore: 0.08,
    color: 0xe2e8f0
  },
  pistol: {
    id: "pistol",
    name: "Civic-9 Sidearm",
    description: "Compact fallback pistol for bad rooms, broken plans, and sidearm-only inserts.",
    raidCost: 35,
    damage: 16,
    pellets: 1,
    spread: 0.08,
    fireInterval: 0.18,
    bulletSpeed: 680,
    range: 360,
    magazineSize: 12,
    reserveAmmo: 36,
    ammoPackAmmo: 18,
    reloadTime: 1.1,
    reloadStyle: "magazine",
    reloadInsertTime: 1.1,
    moveSpeed: 266,
    moveSpreadPenalty: 0.07,
    recoilPerShot: 0.017,
    recoilRecoveryPerSecond: 0.15,
    maxSpreadPenalty: 0.12,
    focusMoveMultiplier: 0.9,
    focusSpreadMultiplier: 0.72,
    focusRecoveryMultiplier: 1.22,
    noiseRadius: 240,
    noiseScore: 0.44,
    color: 0xfda4af
  },
  "worn-ak": {
    id: "worn-ak",
    name: "Worn AK",
    description: "A tired stamped AK with the rear sight half-trusted, the front post bent, and the selector only worth touching in single fire. It works, but never cleanly.",
    raidCost: 48,
    damage: 22,
    pellets: 1,
    spread: 0.128,
    fireInterval: 0.34,
    bulletSpeed: 760,
    range: 590,
    magazineSize: 15,
    reserveAmmo: 45,
    ammoPackAmmo: 18,
    reloadTime: 2.45,
    reloadStyle: "magazine",
    reloadInsertTime: 2.45,
    moveSpeed: 216,
    moveSpreadPenalty: 0.16,
    recoilPerShot: 0.036,
    recoilRecoveryPerSecond: 0.074,
    maxSpreadPenalty: 0.26,
    focusMoveMultiplier: 0.66,
    focusSpreadMultiplier: 0.9,
    focusRecoveryMultiplier: 0.96,
    noiseRadius: 470,
    noiseScore: 0.98,
    color: 0xf59e0b
  },
  "short-mosin": {
    id: "short-mosin",
    name: "Cut-Down Mosin",
    description: "A hacked-short surplus Mosin in rotten shape. No real sight picture, ugly single-round loading, wild kick, and a shoulder fit that lies to you, but it still hits hard if you steal the shot.",
    raidCost: 65,
    damage: 58,
    pellets: 1,
    spread: 0.165,
    fireInterval: 1.34,
    bulletSpeed: 860,
    range: 660,
    magazineSize: 5,
    reserveAmmo: 20,
    ammoPackAmmo: 8,
    reloadTime: 4.2,
    reloadStyle: "shell",
    reloadInsertTime: 0.74,
    moveSpeed: 208,
    moveSpreadPenalty: 0.19,
    recoilPerShot: 0.082,
    recoilRecoveryPerSecond: 0.058,
    maxSpreadPenalty: 0.32,
    focusMoveMultiplier: 0.62,
    focusSpreadMultiplier: 0.78,
    focusRecoveryMultiplier: 0.94,
    noiseRadius: 620,
    noiseScore: 1.48,
    color: 0xd6b38a
  },
  rifle: {
    id: "rifle",
    name: "VKR Rifle",
    description: "Accurate mid-range rifle with disciplined recoil and heavy hits.",
    raidCost: 120,
    damage: 34,
    pellets: 1,
    spread: 0.035,
    fireInterval: 0.24,
    bulletSpeed: 720,
    range: 760,
    magazineSize: 18,
    reserveAmmo: 72,
    ammoPackAmmo: 30,
    reloadTime: 1.4,
    reloadStyle: "magazine",
    reloadInsertTime: 1.4,
    moveSpeed: 228,
    moveSpreadPenalty: 0.08,
    recoilPerShot: 0.024,
    recoilRecoveryPerSecond: 0.12,
    maxSpreadPenalty: 0.16,
    focusMoveMultiplier: 0.72,
    focusSpreadMultiplier: 0.4,
    focusRecoveryMultiplier: 1.45,
    noiseRadius: 500,
    noiseScore: 1.2,
    color: 0xa7f3d0
  },
  smg: {
    id: "smg",
    name: "Kite SMG",
    description: "Fast and forgiving in close rooms, but weaker once the spray opens.",
    raidCost: 95,
    damage: 14,
    pellets: 1,
    spread: 0.13,
    fireInterval: 0.085,
    bulletSpeed: 760,
    range: 520,
    magazineSize: 32,
    reserveAmmo: 128,
    ammoPackAmmo: 48,
    reloadTime: 1.7,
    reloadStyle: "magazine",
    reloadInsertTime: 1.7,
    moveSpeed: 256,
    moveSpreadPenalty: 0.11,
    recoilPerShot: 0.018,
    recoilRecoveryPerSecond: 0.095,
    maxSpreadPenalty: 0.18,
    focusMoveMultiplier: 0.84,
    focusSpreadMultiplier: 0.74,
    focusRecoveryMultiplier: 1.18,
    noiseRadius: 360,
    noiseScore: 0.78,
    color: 0x7dd3fc
  },
  shotgun: {
    id: "shotgun",
    name: "Morrow Shotgun",
    description: "Devastating at extraction doors and corner fights, risky in the open.",
    raidCost: 110,
    damage: 11,
    pellets: 6,
    spread: 0.36,
    fireInterval: 0.72,
    bulletSpeed: 560,
    range: 320,
    magazineSize: 6,
    reserveAmmo: 36,
    ammoPackAmmo: 10,
    reloadTime: 2.1,
    reloadStyle: "shell",
    reloadInsertTime: 0.52,
    moveSpeed: 218,
    moveSpreadPenalty: 0.05,
    recoilPerShot: 0.04,
    recoilRecoveryPerSecond: 0.16,
    maxSpreadPenalty: 0.14,
    focusMoveMultiplier: 0.8,
    focusSpreadMultiplier: 0.68,
    focusRecoveryMultiplier: 1.08,
    noiseRadius: 620,
    noiseScore: 1.6,
    color: 0xfbbf24
  },
  pkm: {
    id: "pkm",
    name: "PKM Support Gun",
    description: "Heavy support gun built to pin lanes, cover crossings, and hold a push together.",
    raidCost: 165,
    damage: 26,
    pellets: 1,
    spread: 0.075,
    fireInterval: 0.11,
    bulletSpeed: 780,
    range: 920,
    magazineSize: 60,
    reserveAmmo: 120,
    ammoPackAmmo: 40,
    reloadTime: 4.8,
    reloadStyle: "magazine",
    reloadInsertTime: 4.8,
    moveSpeed: 194,
    moveSpreadPenalty: 0.12,
    recoilPerShot: 0.03,
    recoilRecoveryPerSecond: 0.09,
    maxSpreadPenalty: 0.22,
    focusMoveMultiplier: 0.62,
    focusSpreadMultiplier: 0.44,
    focusRecoveryMultiplier: 1.26,
    noiseRadius: 760,
    noiseScore: 2.1,
    color: 0xf97316
  },
  amr: {
    id: "amr",
    name: "Bastion AMR",
    description: "Late-war anti-materiel rifle for deleting plated lane anchors and owning long peeks at a brutal handling cost.",
    raidCost: 245,
    damage: 88,
    pellets: 1,
    spread: 0.024,
    fireInterval: 1.18,
    bulletSpeed: 980,
    range: 1180,
    magazineSize: 5,
    reserveAmmo: 20,
    ammoPackAmmo: 8,
    reloadTime: 2.9,
    reloadStyle: "magazine",
    reloadInsertTime: 2.9,
    moveSpeed: 176,
    moveSpreadPenalty: 0.15,
    recoilPerShot: 0.072,
    recoilRecoveryPerSecond: 0.07,
    maxSpreadPenalty: 0.26,
    focusMoveMultiplier: 0.5,
    focusSpreadMultiplier: 0.22,
    focusRecoveryMultiplier: 1.34,
    noiseRadius: 920,
    noiseScore: 2.55,
    color: 0xe2e8f0
  },
  rpg: {
    id: "rpg",
    name: "RPG-7 Launcher",
    description: "Earned siege weapon for cracking camp anchors, bunker mouths, and packed trench lines. Slow, loud, expensive, and decisive.",
    raidCost: 480,
    damage: 150,
    pellets: 1,
    spread: 0.045,
    fireInterval: 2.4,
    bulletSpeed: 460,
    range: 860,
    magazineSize: 1,
    reserveAmmo: 2,
    ammoPackAmmo: 1,
    reloadTime: 4.8,
    reloadStyle: "magazine",
    reloadInsertTime: 4.8,
    moveSpeed: 162,
    moveSpreadPenalty: 0.18,
    recoilPerShot: 0.14,
    recoilRecoveryPerSecond: 0.045,
    maxSpreadPenalty: 0.36,
    focusMoveMultiplier: 0.46,
    focusSpreadMultiplier: 0.34,
    focusRecoveryMultiplier: 1.12,
    noiseRadius: 980,
    noiseScore: 3.4,
    color: 0xfacc15
  }
};
